### PR TITLE
Porting V2 (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by aliang8**

### CODE REVIEW

**Comment by kevinbarabash** [comment]
This feels a bit premature.

**Comment by aliang8** [comment]
Should I close it? I thought it would be better if other people wanted to take a look at it. Not entirely sure.

**Comment by kevinbarabash** [comment]
If people are interested they could follow changes to the `porting` branch.

**Comment by evykassirer** [comment]
this could be helpful for viewing the current diff and talking about it maybe?

definitely shouldn't be merged though, if we keep it open add DO NOT MERGE in the title

side note - kevin are you ok to keep discussing changes on your closed PR? or would here be better?

**Comment by evykassirer** [comment]
THIS WAS DO NOT MERGE!!

**Comment by kevinbarabash** [comment]
@evykassirer sorry for not responding to your question earlier.  We can keep discussing changes on the closed PR.  It might be better to break some of those items out into separate issues.  Also, you may want to create a special tag to mark issues that are specific to the porting process.

**Comment by evykassirer** [comment]
good idea! thanks kevin :)

(also for anyone following along, master is back to it's previous state :) )

**Pull request merged**
