### PR TITLE
Better lone parenthesis handling

### PR DESCRIPTION
**Pull request by GabrielMahan**
https://github.com/socraticorg/mathsteps/issues/249

Hi there! This is my first contribution to mathsteps, so apologies if this is not a very robust solution; happy to investigate further.

### CODE REVIEW

**Comment by evykassirer** [comment]
I really don't remember how anything is set up - are you able to merge it as the one who opened the PR, or do I need to do it? ^^'

**Comment by GabrielMahan** [comment]
@evykassirer thanks for the quick review!! And only those with write-access to the project can merge, so unfortunately I can't merge this myself.

**Comment by evykassirer** [comment]
Yes, that makes sense! Thanks :)

**Comment by GabrielMahan** [comment]
@evykassirer awesome, thanks! Does the version still need to be bumped / the update published to npm?

**Pull request merged**
