### PR TITLE
Refactor isOperator to accept operator parameter

### PR DESCRIPTION
**Pull request by mcarthurgill**
addresses #31 

Added parameter to accept a String operator into isOperator (defaulted to null). Refactored isOperator usage throughout app where applicable. Adequate tests added as well.

### CODE REVIEW

**Comment by evykassirer** [comment]
this is sweet! I've been dreaming of this function for a while, nice to see it existing.

was just looking through for anywhere else it could make sense to use it...

in likeTermCollector `if (!Node.Type.isOperator(node) || !(node.op === '+' || node.op === '*')) ` can just be two calls to isOperator now (I think) which seems cleaner. What do you think?

otherwise looks 👌 👌

**Comment by mcarthurgill** [comment]
Pushed the change. Let me know if that's not what you were thinking.

**Comment by evykassirer** [comment]
yup! that's what I was thinking, much cleaner.

Thanks :)

**Comment by evykassirer** [comment]
hey @mcarthurgill 

I was just wondering if you'd like me to mail you some mathsteps stickers we just got in

img_20170218_173323

if you're interested, email mathsteps@socratic.org with your mailing address and I'll send 'em off to you!

**Pull request merged**
