### PR TITLE
better fix for multiplying like term constant nodes

### PR DESCRIPTION
**Pull request by ldworkin**
https://github.com/socraticorg/mathsteps/pull/180#discussion_r125961158

### CODE REVIEW

**Comment by evykassirer** [comment]
thanks for updating this!

also can you add a test somewhere that failed before and doesn't anymore? tests in this repo are usually fairly quick to add, should just be one line of asciimath input/out example.

**Comment by ldworkin** [comment]
What would that test look like @evykassirer ? Cause the simplification was still "correct" before, as in the final answer was fine, but the steps it took to get there were excessive.

**Comment by evykassirer** [comment]
Oh sorry - true. I'd recommend using `TestUtil.testSubsteps`

**Comment by evykassirer** [comment]
oo maybe `simplifyExpression/oneStep.test.js`

**Comment by aliang8** [comment]
Thanks! This looks cleaner.

**Comment by evykassirer** [comment]
sweet! glad that was easy

**Pull request merged**
