### PR TITLE
Fixes for Kevin's Init PR

### PR DESCRIPTION
**Pull request by aliang8**
updates from code review to #167

deleted some comments
removed `isPolynomialTerm` because it exists now in `math-nodes`

### CODE REVIEW

**Comment by evykassirer** [comment]
is this ready for me to review? looks like you haven't addressed all the comments yet. 

lemme know when? :)

**Comment by evykassirer** [comment]
you said it was ready, so here are remaining comment to be addressed:

- [ ] removing hasUnsupportedNodes : https://github.com/socraticorg/mathsteps/pull/167/files#r123909501
- [ ] finish conversation about abs check for arg length: https://github.com/socraticorg/mathsteps/pull/167/files#r123319914
- [ ] https://github.com/socraticorg/mathsteps/pull/167/files#r123317967 if you keep hasUnsupportedNodes, can clean up
- [ ] https://github.com/socraticorg/mathsteps/pull/167/files#r123317429 if you keep hasUnsupportedNodes
- [ ] https://github.com/socraticorg/mathsteps/pull/167/files#r123408188 add a `isParens` to query from math-nodes

I'm not gonna keep going cause I'm pretty much copy pasting every comment :p  so if you could look at all the comments in https://github.com/socraticorg/mathsteps/pull/167/files and make sure all the comments have been addressed (you can continue the conversation there) that'd be great thanks!

**Comment by kevinbarabash** [comment]
@evykassirer @aliang8 I've updated `math-nodes` to do arity checks on most of the operators, see https://github.com/semantic-math/math-nodes/commit/131d5c36fc1cbc88e699eef060a078d8f130976d.  I was thinking of adding checks for `mul` and `add` to make sure `args.length > 1`.  Thoughts?

**Comment by evykassirer** [comment]
@kevinbarabash I like that!

**Pull request closed without merging**
