### PR TITLE
Add pre-commit hook to run tests & linter

### PR DESCRIPTION
**Pull request by hmaurer**
Tiny PR resolving https://github.com/socraticorg/mathsteps/issues/30. There seemed to be two eslint infractions in the codebase so I fixed those in the same commit. After cloning the repository one has to run `npm run setup-hooks` to symlink the pre-commit hook from `scripts/git-hooks/pre-commit` to `.git/hooks/pre-commit` and it should work from there.

### CODE REVIEW

**Comment by evykassirer** [comment]
sweet! I'll check it out later today.

can you add `npm run setup-hooks` to the instructions in CONTRIBUTING.md too?

**Comment by hmaurer** [comment]
Yes; done.

**Comment by hmaurer** [comment]
Sorry, I made this PR from master but it turned out to be a bad idea if I am working on different things in parallel. I'll re-open a PR from another branch. Feel free to delete this one.

**Comment by evykassirer** [comment]
I don't think I can delete pull requests - besides, they're good record of the old conversation we had. I'll link to it from the other issue.

Also good call on using branches - I think that's the main benefit of them and not doing stuff on master, so it was a perfect learn by example haha ^_^

**Pull request closed without merging**
